### ISSUE TITLE
Implement Tree Data Structure for representing data.

### ISSUE THREAD

**Issue by 5hirish** [5hirish/adam_qas#1]
A **tree** can be used in order to represent the association and relation between the primary topic and its related topics. Any one of the related topics can later act as a primary topic for some another query targeted to that topic.
eg. _When did Linus release the fist prototype of Linux ?_
`[Linus] -> [Linux], [Git], [Subsurface], [Linux Foundation], [Finland]`.....
Here [Linus] is the root node and [Linux], [Git], [Subsurface], [Linux Foundation], [Finland] are the nodes of the tree at level 1.
Now if the next question posed is : _Which is the license of Linux ?_
Now we can easily pursue the node [Linux] furthermore considering it as a root node for the current question. 
`[Linux] -> [Linus], [Android], [GPL 2]`......
Thus we can maintain the context throughout the interaction with the system without; it making us feel as lost.

**Comment by amitgunjal26** [comment]
As we discussed with the guide and focusing more on Information Retrieval so the issue is closed tentatively. Will create a new one on the two major ends we are currently handling.

**Comment by 5hirish** [comment]
@amitgunjal26  Please, open a new issue regarding the IR and specify all the details and progress in it also include the explanation I gave on that da in college on your book. So, it will be clear.
