### ISSUE TITLE
Question Answering

### ISSUE THREAD

**Issue by jochem4207** [5hirish/adam_qas#11]
Super epic piece of python! It took me a while to get it work (tried windows) but now on linux mint it's working!

The question classification works epicly well (if I don't do weird things like WHERE is amsterdam?). I'm looking into this library for my final internship and am amazed! The only thing I notice is that the answers are often quite weird. Some are fine some are not even close. Is this known? I know it is work in progress tho.

An example is below (the question is copied from commented code in the feature_extractor.py

using spacy 1.9! 
```
Q:>What's the American dollar equivalent for 8 pounds in the U.K. ?
Question: What's the American dollar equivalent for 8 pounds in the U.K. ?
Class: ['DESC']
Question Features: ['equivalent american dollar', '8', 'pounds', 'U.K.', 'be']
Question Query: [['equivalent american dollar', '8', 'pounds', 'U.K.', 'be'], [], [], []]
Fetching Knowledge source...
Pages Fetched: 11
Documents pre-processed
Ranked Pages: [(0, 0.21964739), (2, 0.20715606), (3, 0.19018666)]
Searching:  ['american dollar', '8', 'dollar', 'american', 'u.k.', 'equivalent american dollar', 'equivalent american', 'be', 'pounds', 'equivalent']
Candidate Answer: (5) ['Kate Plus 8 is an American reality television show.', 'American trade dollars are 90% silver and weigh 420 grains (27.2 g), which is about 0.5 g heavier than the regular circulation Seated Liberty Dollars and Morgan Dollars.', 'The opening ceremony of the Summer Olympics in Beijing started at 8 seconds and 8 minutes past 8 pm (local time) on 8 August 2008.', 'The currency was ultimately replaced by the silver dollar at the rate of 1 silver dollar to 1000 continental dollars.', 'The Sacagawea dollar is one example of the copper alloy dollar.']
Answer: Kate Plus 8 is an American reality television show. American trade dollars are 90% silver and weigh 420 grains (27.2 g), which is about 0.5 g heavier than the regular circulation Seated Liberty Dollars and Morgan Dollars. The opening ceremony of the Summer Olympics in Beijing started at 8 seconds and 8 minutes past 8 pm (local time) on 8 August 2008. The currency was ultimately replaced by the silver dollar at the rate of 1 silver dollar to 1000 continental dollars. The Sacagawea dollar is one example of the copper alloy dollar.
Total time : 20.559940099716187
```

Process finished with exit code 0

```
Q:>How many colored squares are there on a Rubik's Cube
Question: How many colored squares are there on a Rubik's Cube
Class: ['NUM']

Question Features: ['colored squares', 'Rubik', 'Cube', 'be']
Question Query: [['colored squares', 'Rubik', 'Cube', 'be'], [], [], []]
Fetching Knowledge source...
Pages Fetched: 7
Documents pre-processed
Ranked Pages: [(3, 0.54112279), (5, 0.32183689), (4, 0.27689046)]
Searching:  ['cube', 'squares', 'be', 'rubik', 'colored', 'colored squares']
Candidate Answer: (5) ["Tesseract Trapezohedron Miscellaneous cubes Cube (film) Diamond cubic Lövheim cube of emotion Cube of Heymans Necker Cube OLAP cube Prince Rupert's cube Rubik's Cube The Cube (game show) Unit cube Yoshimoto Cube Kaaba 'Rubik's Cube is a 3-D combination puzzle invented in 1974 by Hungarian sculptor and professor of architecture Ernő Rubik.", 'ISBN 157912805X. Official website Safecracker Method: Solving Rubik\'s Cube with just 10 Numbers Rubik\'s Cube at DMOZ How to solve a Rubik\'s Cube on YouTube World record 5.55 second solution on YouTube World Cube Association List of related puzzles and solutions Complete disassembly of a 3^3 classic Rubik\'s cube Speedsolving Wiki "Rubik\'s Cube". Google Doodle. Retrieved 2014-05-19.', "Mathematics of the Rubik's Cube Design.", 'Google has released the Chrome Cube Lab in association with Ernő Rubik.', "Ideal rebranded The Magic Cube to the Rubik's Cube before its introduction to an international audience in 1980."]
Answer: Tesseract Trapezohedron Miscellaneous cubes Cube (film) Diamond cubic Lövheim cube of emotion Cube of Heymans Necker Cube OLAP cube Prince Rupert's cube Rubik's Cube The Cube (game show) Unit cube Yoshimoto Cube Kaaba 'Rubik's Cube is a 3-D combination puzzle invented in 1974 by Hungarian sculptor and professor of architecture Ernő Rubik. ISBN 157912805X. Official website Safecracker Method: Solving Rubik's Cube with just 10 Numbers Rubik's Cube at DMOZ How to solve a Rubik's Cube on YouTube World record 5.55 second solution on YouTube World Cube Association List of related puzzles and solutions Complete disassembly of a 3^3 classic Rubik's cube Speedsolving Wiki "Rubik's Cube". Google Doodle. Retrieved 2014-05-19. Mathematics of the Rubik's Cube Design. Google has released the Chrome Cube Lab in association with Ernő Rubik. Ideal rebranded The Magic Cube to the Rubik's Cube before its introduction to an international audience in 1980.
Total time : 16.014000177383423
```

**Comment by 5hirish** [comment]
The reason why it shows such poor results is that:
1) The _Co-reference resolution_ is not implemented. Hence, sentences like "It has 54 colored square" end-up having a low score as the Vector Space Model is unable to figure out what "It" represents here...
2) The project currently only uses _Wikipedia_ as its knowledge source. And the Wikipedia page on Rubik's cube doesn't have the answer to this question. [Rubik's Cube](https://en.wikipedia.org/wiki/Rubik%27s_Cube)
3) VSM implemented here needs tunning. I couldn't figure out (example) how to increase the weight of terms like "Rubick" as compared to the cube. VSM is supposed to take care of this issue using IDF but in some cases, it doesn't look like it is.

In the case of the 1st question "What's the American dollar equivalent for 8 pounds in the U.K. ?" I haven't implemented the logic to handle calculational questions. Since there are still lots of stuff to be done to fix the factual question answering, this isn't prioritized.

**Comment by 5hirish** [comment]
To help you jump start with Co-reference resolution, take a look at this repo: [huggingface/neuralcoref](https://github.com/huggingface/neuralcoref) . I tried, it but the _neuralcoref_ could not handle Wiki Docs. I think it is meant for a few sentences.
Also, the [Wikipedia API](https://pypi.python.org/pypi/wikipedia/) used in this project is now no longer maintained and hence are crippled. But very soon I am planning to replace them with my own Wikipedia scrapper.

**Comment by jochem4207** [comment]
At work we've chosen not to use python so there won't be much contributions from me. Tho I think it would be useful to either link to : https://shirishkadam.com/2017/07/03/nlp-question-classification-using-support-vector-machines-spacyscikit-learnpandas/ or add installation instructions in the readme. Since they are pretty hard to find

**Comment by 5hirish** [comment]
Updated README and other documentations.
