### ISSUE TITLE
mapper_parsing_exception error

### ISSUE THREAD

**Issue by ArzaEshita** [5hirish/adam_qas#38]
I am using elastic search version 6.1.1 & Python - 3.6.4

I am getting a mapping_parser_exception error when trying to run the code. Below is the error :

    ERROR:qas.esstore.es_connect:Error Occurred in Index creation:
    {
        'error': 
        {
            'root_cause': 
            [{
                'type': 'mapper_parsing_exception', 
                'reason': 'Root mapping definition has unsupported parameters:  [article : {_meta={version=2}, properties={content_table={analyzer=adam_analyzer, type=text}, raw={type=object, enabled=false}, content_info={analyzer=adam_analyzer, type=text}, title={analyzer=adam_analyzer, type=text}, updated={type=date}, content={analyzer=adam_analyzer, type=text}, revision={type=long}}}]'
            }],
            'type': 'mapper_parsing_exception', 
            'reason': 'Failed to parse mapping [_doc]: Root mapping definition has unsupported parameters:  [article : {_meta={version=2}, properties={content_table={analyzer=adam_analyzer, type=text}, raw={type=object, enabled=false}, content_info={analyzer=adam_analyzer, type=text}, title={analyzer=adam_analyzer, type=text}, updated={type=date}, content={analyzer=adam_analyzer, type=text}, revision={type=long}}}]', 
            'caused_by': 
            {
                'type': 'mapper_parsing_exception', 
                'reason': 'Root mapping definition has unsupported parameters:  [article : {_meta={version=2}, properties={content_table={analyzer=adam_analyzer, type=text}, raw={type=object, enabled=false}, content_info={analyzer=adam_analyzer, type=text}, title={analyzer=adam_analyzer, type=text}, updated={type=date}, content={analyzer=adam_analyzer, type=text}, revision={type=long}}}]'
            }
        }, 
        'status': 400
    }

How to fix this ?

**Comment by idoroiengel** [comment]
@ArzaEshita did you start the elasticsearch service properly and all?

**Comment by ArzaEshita** [comment]
@idoroiengel I started it in another terminal. Is that the way to start it ?

**Comment by idoroiengel** [comment]
@ArzaEshita I don't think it matters on which terminal you started it. The service runs on port 9200.
insert in your browser http://localhost:9200 and if you get a response that means the service is working.

**Comment by 5hirish** [comment]
@ArzaEshita this is mapping error, means, elasticsearch is not able to create the index with the given mapping. This is probably due to version conflict with elasticsearch. As the mapping I built might not be compatible with the version of elasticsearch you are running. I will check that today if that's the case I will freeze the version and update the docs or else will try to resolve this error.

**Comment by 5hirish** [comment]
@ArzaEshita I have tested the mapping on elasticsearch-6.1.2 and on elasticsearch-6.2.3. I haven't faced any such issues in creating the index. You should probably try upgrading your elasticsearch to 6.1.2 from 6.1.1 and it should be quite easy.
