### ISSUE TITLE
Update Dockerfile

### ISSUE THREAD

**Issue by ZiggerZZ** [5hirish/adam_qas#42]
Hi!
Could you also update the Dockerfile, please? Yours doesn't work for me.
I can provide the logs if you wish but I suppose that the Dockerfile is just not up to date (updated last time 1 year ago).
Thanks!

**Comment by 5hirish** [comment]
@ZiggerZZ logs would be awesome if you have any.

**Comment by ZiggerZZ** [comment]
Until step 10 everything runs fine, then:

```
Step 10/19 : RUN echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" >> /etc/apt/sources.list &&     echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" >> /etc/apt/sources.list &&     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C2518248EEA14886 &&     apt-get update &&     echo oracle-java${JAVA_VER}-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections &&     apt-get install -y --force-yes --no-install-recommends oracle-java${JAVA_VER}-installer oracle-java${JAVA_VER}-set-default &&     apt-get clean &&     rm -rf /var/cache/oracle-jdk${JAVA_VER}-installer

 ---> Running in ca718e357669
Executing: gpg --ignore-time-conflict --no-options --no-default-keyring --homedir /tmp/tmp.bxzEBmHkGY --no-auto-check-trustdb --trust-model always --primary-keyring /etc/apt/trusted.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-jessie-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-security-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-stretch-stable.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-automatic.gpg --keyring /etc/apt/trusted.gpg.d/debian-archive-wheezy-stable.gpg --keyserver keyserver.ubuntu.com --recv-keys C2518248EEA14886

gpg: requesting key EEA14886 from hkp server keyserver.ubuntu.com
gpg: key EEA14886: public key "Launchpad VLC" imported
gpg: Total number processed: 1
gpg:               imported: 1  (RSA: 1)

Get:1 http://ppa.launchpad.net trusty InRelease [15.5 kB]
Get:2 http://security.debian.org jessie/updates InRelease [44.9 kB]
Ign http://deb.debian.org jessie InRelease
Get:3 http://deb.debian.org jessie Release.gpg [2420 B]
Get:4 http://deb.debian.org jessie Release [148 kB]
Get:5 http://ppa.launchpad.net trusty/main Sources [20 B]
Get:6 http://security.debian.org jessie/updates/main amd64 Packages [849 kB]
Get:7 http://ppa.launchpad.net trusty/main amd64 Packages [20 B]
Get:8 http://deb.debian.org jessie/main amd64 Packages [9098 kB]
Fetched 10.2 MB in 12s (837 kB/s)
Reading package lists...
Reading package lists...
Building dependency tree...
Reading state information...

E: Unable to locate package oracle-java8-installer
E: Unable to locate package oracle-java8-set-default

The command '/bin/sh -c echo "deb http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" >> /etc/apt/sources.list &&     echo "deb-src http://ppa.launchpad.net/webupd8team/java/ubuntu trusty main" >> /etc/apt/sources.list &&     apt-key adv --keyserver keyserver.ubuntu.com --recv-keys C2518248EEA14886 &&     apt-get update &&     echo oracle-java${JAVA_VER}-installer shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections &&     apt-get install -y --force-yes --no-install-recommends oracle-java${JAVA_VER}-installer oracle-java${JAVA_VER}-set-default &&     apt-get clean &&     rm -rf /var/cache/oracle-jdk${JAVA_VER}-installer' returned a non-zero code: 100

```

**Comment by 5hirish** [comment]
@ZiggerZZ the java installation step needs to be updated > https://github.com/5hirish/adam_qas/blob/master/Dockerfile#L21 
If you figure it out please create a PR.

**Comment by ZiggerZZ** [comment]
@5hirish by the way I didn't figure out why you need java... I haven't found any code in the repo that calls java functions.

**Comment by 5hirish** [comment]
Elasticsearch dependency.

**Comment by ZiggerZZ** [comment]
What if using a java image [https://hub.docker.com/_/openjdk/](url) and install python there or even directly use a python+java image [https://hub.docker.com/r/rappdw/docker-java-python/](url)?

**Comment by 5hirish** [comment]
Yes, we can go with OpenJDK v8 image, probably should even upgrade the Debian version: `8-jdk-stretch`. The current Elasticsearch version 6.X depends on Java8

**Comment by 5hirish** [comment]
Also, I just read that the newer version of Elasticsearch 7.X has a bundled version of OpenJDK with it. I will try to upgrade it. If everything is fine we won't have to maintain Java. But for now, you can go with OpenJDK image and install Python 3.5 with it.

**Comment by 5hirish** [comment]
@ZiggerZZ I have successfully updated the Elasticsearch version from 6.2 to 7.1, Will try to fix the Docker config now.

**Comment by 5hirish** [comment]
Fixed this.

**Comment by ZiggerZZ** [comment]
Thanks!

**Comment by ZiggerZZ** [comment]
@5hirish Does it work for you?
When I run `docker run adam "What is Linux?"` I get
```
docker: Error response from daemon: OCI runtime create failed: container_linux.go:344: starting container process caused "exec: \"What is Linux?\": executable file not found in $PATH": unknown.

ERRO[0001] error waiting for container: context canceled
```
Am I launching the container correctly? Maybe the flag in `CMD` should be changed to `-vv`?

**Comment by 5hirish** [comment]
I am not that well versed with Docker, but I will look into this over the weekend.

**Comment by ZiggerZZ** [comment]
@5hirish the issue is with elasticsearch: when ran in the container, returns `ERROR:qas.esstore.es_connect:Elasitcsearch is not installed or its service is not running.`
I'm trying to use an elasticsearch image now to create an image for Adam.

**Comment by 5hirish** [comment]
@ZiggerZZ I think the Dockerfile needs to be updated to RUN the elasticsearch service, also might need to add some delay for the service to start.

**Comment by ZiggerZZ** [comment]
@5hirish I think since the right solution is to split the Dockerfile into two: one with Elasticsearch and one with adam, after use docker-compose.

**Comment by 5hirish** [comment]
Is this possible? If we can separate dependencies like this, it would be awesome.

**Comment by ZiggerZZ** [comment]
I think so.
https://alysivji.github.io/elasticsearch-kibana-with-docker-compose.html here’s an example of how to run Elasticsearch and Kibana in two different containers, might help.

**Comment by 5hirish** [comment]
@ZiggerZZ If you address this issue in your fork, please create a PR.

**Comment by 5hirish** [comment]
@ZiggerZZ Awesome man !!!
